# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.quarkus.jvm.buildpack"
version = "0.0.1"
name = "Quarkus JVM Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.quarkus.jvm"
